version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: security_db
      MYSQL_USER: security
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


